### ISSUE TITLE
/result endpoint - Authentication failed

### ISSUE THREAD

**Issue by sevket** [verifykit/verifykit-sdk-php#13]
I'm successfully getting sessionId with /check endpoint but /result endpoint always returns
"httpStatusCode": 403,
"errorMessage": "Authentication failed.",
"errorCode": "403001"

for eaxample ;
/check response is ;
{
    "meta": {
        "requestId": "REQUEST-ID",
        "httpStatusCode": 200
    },
    "result": {
        "validationStatus": true,
        "sessionId": "uvP7CCDz3Ug3xpS",
        "appPlatform": "rest"
    }
}

/result request is;
curl --location --request POST 'https://web-rest.verifykit.com/v1.0/result' \
--header 'X-Vfk-Server-Key: YOUR-SERVER-KEY' \
--header 'X-Vfk-Forwarded-For: END-USER-IP-ADDRESS' \
--header 'Content-Type: application/json' \
--data-raw '{
    "sessionId": "uvP7CCDz3Ug3xpS"
}'

response;

{
    "meta": {
        "requestId": "REQUEST-ID",
        "httpStatusCode": 403,
        "errorMessage": "Authentication failed.",
        "errorCode": "403001"
    }
}

**Comment by emir-memmi** [comment]
Hi @sevket , you are sending /result request to the wrong domain. /result request should be sent to **https://api.verifykit.com/v1.0/result** . If the problem persists, please contact us again.

**Comment by sevket** [comment]
> Hi @sevket , you are sending /result request to the wrong domain. /result request should be sent to **https://api.verifykit.com/v1.0/result** . If the problem persists, please contact us again.

Thank you very much. it works.
