### ISSUE TITLE
$validationMethod-> getName returning null?

### ISSUE THREAD

**Issue by kadirgecit** [verifykit/verifykit-sdk-php#5]
$validationMethod-> getName, getApp, getText, getTextColour, getBgColour, getIcon...

all theese items returning null..

```
foreach ($validationMethodList->getList() as $validationMethod) {
    
   echo $validationMethod-> getName;
    
    // $validationMethod-> getName, getApp, getText, getTextColour, getBgColour, getIcon...
}
```

**Comment by gokhantunckale** [comment]
Can you share all the code you use with me? If you use it like this, the items should not be null
```php
$vfk = new \VerifyKit\Web($serverKey, $clientIp);

/** @var \VerifyKit\Entity\ValidationMethodList $validationMethodList */
$validationMethodList = $vfk->getValidationMethodList();

/** @var \VerifyKit\Entity\ValidationMethod $validationMethod */
foreach ($validationMethodList->getList() as $validationMethod) {
    // $validationMethod-> getName, getApp, getText, getTextColour, getBgColour, getIcon...
}
```

**Comment by kadirgecit** [comment]
> Can you share all the code you use with me @kadirgecit ? If you use it like this, the items should not be null
> 
> ```
> $vfk = new \VerifyKit\Web($serverKey, $clientIp);
> 
> /** @var \VerifyKit\Entity\ValidationMethodList $validationMethodList */
> $validationMethodList = $vfk->getValidationMethodList();
> 
> /** @var \VerifyKit\Entity\ValidationMethod $validationMethod */
> foreach ($validationMethodList->getList() as $validationMethod) {
>     // $validationMethod-> getName, getApp, getText, getTextColour, getBgColour, getIcon...
> }
> ```

This is the full code:

`<?php

require 'vendor/autoload.php';

$serverKey = "####myserverkey####";

if (!empty($_SERVER['HTTP_CLIENT_IP'])) {
    $clientIp = $_SERVER['HTTP_CLIENT_IP'];
} elseif (!empty($_SERVER['HTTP_X_FORWARDED_FOR'])) {
    $clientIp = $_SERVER['HTTP_X_FORWARDED_FOR'];
} else {
    $clientIp = $_SERVER['REMOTE_ADDR'];
}

$vfk = new \VerifyKit\Web($serverKey, $clientIp);

/** @var \VerifyKit\Entity\ValidationMethodList $validationMethodList */
$validationMethodList = $vfk->getValidationMethodList();

foreach ($validationMethodList->getList() as $validationMethod) {
    
   echo $validationMethod-> getName;
    
    // $validationMethod-> getName, getApp, getText, getTextColour, getBgColour, getIcon...
}
`

**Comment by kadirgecit** [comment]
This is the full code: 

`require 'vendor/autoload.php';
$serverKey = "myserverkey";

if (!empty($_SERVER['HTTP_CLIENT_IP'])) {
    $clientIp = $_SERVER['HTTP_CLIENT_IP'];
} elseif (!empty($_SERVER['HTTP_X_FORWARDED_FOR'])) {
    $clientIp = $_SERVER['HTTP_X_FORWARDED_FOR'];
} else {
    $clientIp = $_SERVER['REMOTE_ADDR'];
}

$vfk = new \VerifyKit\Web($serverKey, $clientIp);

/** @var \VerifyKit\Entity\ValidationMethodList $validationMethodList */
$validationMethodList = $vfk->getValidationMethodList();

foreach ($validationMethodList->getList() as $validationMethod) {
    
   echo $validationMethod-> getName;
    
    // $validationMethod-> getName, getApp, getText, getTextColour, getBgColour, getIcon...
}
`

**Comment by gokhantunckale** [comment]
You can solve the problem by using the code block below. In the foreach cycle after you fetch the validationMethod data, you can get the variables using class getters rather than accessing variables directly.

```php

/** @var \VerifyKit\Entity\ValidationMethodList $validationMethodList */
$validationMethodList = $vfk->getValidationMethodList();

foreach ($validationMethodList->getList() as $validationMethod) {
    echo "Validation method params: <br>";
    echo "Name : " . $validationMethod->getName() . "<br>";
    echo "App : " . $validationMethod->getApp() . "<br>";
    echo "Text: " . $validationMethod->getText() . "<br>";
    echo "Text Colour: " . $validationMethod->getTextColour() . "<br>";
    echo "Icon Path: " . $validationMethod->getIconPath() . "<br>";
}

```

Also, when I check the account you have used, I can see that you have received a successful response. If you continue to have problems, I kindly ask you to send an e-mail to support@verifykit.com, we will do our best to help
